* Dependencies

For a particular system, there is some set of software that is required in order to build the Lensor Compiler Collection. This file provides, per system, the command(s) to fetch that software.

* Fedora

NOTE: We don't install =development-tools= group because it includes subversion, systemtap, and a few other things we don't actually use or need. The idea here is to provide the minimal list that is required, not just provide a command that makes it work. If that were the goal, installing every package available from your package manager would be a viable solution...

Base:
#+begin_src shell
  sudo dnf install \
       cmake \
       gcc \
       gcc-c++ \
       git \
       libstdc++-devel \
       make
#+end_src

Test:
#+begin_src shell
  sudo dnf install \
       emacs \
       libcxx \
       libcxx-devel \
       libcxxabi \
       libcxxabi-devel \
       mingw64-gcc \
       mingw64-gcc-c++ \
       mingw64-libstdc++ \
       ucrt64-gcc \
       ucrt64-gcc-c++ \
       ucrt64-libstdc++
#+end_src

* Debian

NOTE: it is possible to build LCC on Ubuntu (and maybe other Debian-based distros)

Base:
#+begin_src shell
  sudo apt install \
       cmake \
       gcc \
       g++ \
       git \
       make
#+end_src

NOTE: testing UCRT toolchains is not available on Ubuntu due to lack of corresponding packages

Test:
#+begin_src shell
  sudo apt install \
       emacs-nox \
       llvm \
       clang \
       libc++-dev \
       libc++-dev \
       gcc-mingw-w64 \
       g++-mingw-w64 \
       gcc-mingw-w64-ucrt64 \
       g++-mingw-w64-ucrt64
#+end_src

* Void Linux (both glibc and musl)

Base:
#+begin_src shell
  sudo xbps-install \
       cmake \
       gcc \
       git \
       make
#+end_src

Test:
#+begin_src shell
  sudo xbps-install \
       emacs \
       llvm \
       clang \
       libcxx-devel \
       libcxxabi-devel \
       cross-x86_64-w64-mingw32ucrt \
       cross-x86_64-w64-mingw32
#+end_src

* Alpine Linux

Base:
#+begin_src shell
  apk add build-base cmake git
#+end_src

Test:
#+begin_src shell
  apk add \
      clang \
      emacs-nox \
      libc++ \
      libc++-dev \
      lld \
      llvm
#+end_src
