# -*- mode: org ; eval: (olivetti-mode 1) -*-

* LCC

- [Meta]: Flatten source structure, re-organize into folders as necessary
- [Driver]: =-gcc= compatibility layer: args after are parsed as GCC arguments
- [Register Allocation]: Register classes (floats/scalar)
  Unspecified and float
- [Register Allocation]: Register (un)spilling
  I need to create an LCC IR source that will cause spilling to happen; I currently can't really figure out how to get Glint to generate code that needs it...
- [Driver]: =--color-theme <file>= option to remap ANSI/VT100 emitted terminal codes to different colors (i.e. BoldRed -> Green) if you want green errors for some reason.
- [LangTest]: fail test specifier given an expected error id in brackets
  i.e. =:fail_sema["invalid-literal/integer"]= or something to make sure the /expected/ diagnostic is emitted, not just a similar one.
- [Register Allocation]: ISel should mark call instructions as clobbering a unique "volatile registers" register (similar to return register), such that RA knows whats up, and could even insert spills before and after the call if necessary.

* Glint

- [Sema]: =print= handle enum value, print enum name
- [Parser/Sema]: Switch on value
- [Sema]: Fix deproceduring of one side of binary operation: =foo : int() 69; foo + 27;=
- [Parser/Sema]: =T.bits=, =T.bytes=, =T.align=
- [Sema]: =import= namespacing
  Basically, I want to allow "hiding" the exports of an imported module behind a "fake" structure.
  "import foo as bar;"
- [Parser/Sema]: Unary operator (keyword) for asserting compile time evaluation
- [Parser/Sema]: =embed "path";= -> string literal of file contents
- [Sema]: =maps_arguments= function attribute

- [Parser]: Warn when multiple expressions appear on one line
- [Parser/Sema]: Compile-time Checked Interpolation: =printf "value: {}\n", 69;=
  This won't be different from =print=, I just like this style of doing
  things (and a lot of people tend to prefer it over splitting strings).
  This will lower into a =print= call, splitting the format string into
  relevant string literals (split on `{}`).
- [Sema]: =out;= as first expression of function body becomes declaration of return type
- [Meta]: glintlang website
- [Sema]: Use intrinsic memset for initialisation (optimisation)
- [Sema]: Variable Entanglement
- [Sema]: Dynamic array of =expr=. =for e in exprs, apply foo, e;= type of thing.
- [Parser]: Block comments
- [Parser/Sema]: Tokens in the AST
- [Diags]: Get rid of "Miscellaneous" ErrorId
- [Lexer]: Case Insensitivity
  Behind =---case-insensitive= flag?
- [Parser/Sema]: Recursive Lambda
- [Parser/Sema]: Named scopes
- [Module]: =---ast-binary= to emit binary representation of AST

  My thought is that a build system could hash the AST instead of the source, so that trivial changes in whitespace or formatting would not actually cause an invalidation.

  In this same vein, =---ast-langtest= to get the LISP-like AST output used in LangTest.
- [Meta]: Fix abuse of =ast.hh=

  It's just far too far-reaching, all-encompassing.
- [Sema]: =---no-default-handlers=
  If passed, do not include definitions for the functionality that Sema generates calls to, for example (i.e. =__dynarray_grow=).
