# -*- mode: org ; eval: (olivetti-mode 1) -*-

* LCC

- [Driver]: Triple-dash =---= arguments passed to front-end (i.e. =---allow-unions= for Glint).
- [Diags]: Error IDs
- [Meta]: Flatten source structure, re-organize into folders as necessary
- [Driver]: =-gcc= compatibility layer: args after are parsed as GCC arguments
- [Register Allocation]: Register classes (floats/scalar)
- [Register Allocation]: Register (un)spilling
- [Driver]: =--color-theme <file>= option to remap ANSI/VT100 emitted terminal codes to different colors (i.e. BoldRed -> Green) if you want green errors for some reason.

* Glint

- [Lexer]: Case Insensitivity
- [Parser]: Number Parsing Bugfix: =069=
- [Sema]: Variable Entanglement
- [Sema]: Fix deproceduring of one side of binary operation: =foo : int() 69; foo + 27;=
- [Sema]: =out;= as first expression of function body becomes declaration of return type
- [Sema]: Use intrinsic memset for initialisation (optimisation)
- [Meta]: glintlang website
- [Parser]: Syntax for asserting compile time evaluation
- [Sema]: =type= type
- [Parser/Sema]: =T.bits=, =T.bytes=, =T.align=
- [Sema]: Dynamic array of =expr=. =for e in exprs, apply foo e;= type of thing.
- [Sema]: =maps_arguments= function attribute
- [Parser/Sema]: Compile-time Checked Interpolation: =printf "value: {}\n", 69;=
- [Parser/Sema]: =embed "path";= -> string literal of file contents
- [Parser]: Disambiguate named type vs value declarations. =bar : struct ...= is a value, =bar ﻿:: struct ...= is a type.
- [Parser/Sema]: Function templates via =auto= parameters
- [Sema]: =print= handle enum value, print enum name
- [Sema]: =import= namespacing
- [Parser]: Block comments
- [Parser/Sema]: Tokens in the AST
- [Parser/Sema]: Switch on value
