# -*- mode: org ; eval: (olivetti-mode 1) -*-

* LCC

- [Meta]: Flatten source structure, re-organize into folders as necessary
- [Driver]: =-gcc= compatibility layer: args after are parsed as GCC arguments
- [Register Allocation]: Register classes (floats/scalar)
- [Register Allocation]: Register (un)spilling
  I need to create an LCC IR source that will cause spilling to happen; I currently can't really figure out how to get Glint to generate code that needs it...
- [Driver]: =--color-theme <file>= option to remap ANSI/VT100 emitted terminal codes to different colors (i.e. BoldRed -> Green) if you want green errors for some reason.
- [LangTest]: fail test specifier given an expected error id in brackets
  i.e. =:fail_sema["invalid-literal/integer"]= or something to make sure the /expected/ diagnostic is emitted, not just a similar one.
- [Register Allocation]: ISel should mark call instructions as clobbering a unique "volatile registers" register (similar to return register), such that RA knows whats up, and could even insert spills before and after the call if necessary.

* Glint

- [Parser/Sema]: Compile-time Checked Interpolation: =printf "value: {}\n", 69;=
  This won't be different from =print=, I just like this style of doing
  things (and a lot of people tend to prefer it over splitting strings).
  This will lower into a =print= call, splitting the format string into
  relevant string literals (split on `{}`).
- [Parser/Sema]: Function templates via =auto= parameters
- [Sema]: Better error when accessing member of a struct with no members
  The current is kind of awkward...
- [Sema]: =print= handle enum value, print enum name
- [Parser/Sema]: Switch on value
- [Sema]: Fix deproceduring of one side of binary operation: =foo : int() 69; foo + 27;=
- [Parser/Sema]: Recursive Lambda
- [Sema]: =out;= as first expression of function body becomes declaration of return type
- [Sema]: Use intrinsic memset for initialisation (optimisation)
- [Parser]: Syntax for asserting compile time evaluation
- [Meta]: glintlang website
- [Sema]: Variable Entanglement
- [Parser/Sema]: =T.bits=, =T.bytes=, =T.align=
- [Sema]: Dynamic array of =expr=. =for e in exprs, apply foo e;= type of thing.
- [Sema]: =maps_arguments= function attribute
- [Parser/Sema]: =embed "path";= -> string literal of file contents
- [Sema]: =import= namespacing
- [Parser]: Block comments
- [Parser/Sema]: Tokens in the AST
- [Diags]: Get rid of "Miscellaneous" ErrorId
- [Lexer]: Case Insensitivity
  Behind =---case-insensitive= flag?
- [Parser/Sema]: Recursive Lambda
- [Parser/Sema]: Named scopes
