// Compile like `cc code.S c_ffi.c`
//   where `code.S` is assembly generated by Intercept compiling `c_ffi.int`,
//   and `cc` refers to a working C compiler, like `gcc` or `clang`.

#include <stdint.h>

typedef struct Numbers {
  intptr_t x;
  intptr_t y;
} Numbers;

/// This is an Intercept function that will be called from C.
extern intptr_t sum_two_impl(Numbers numbers);

/// This is a C function that will be called from Intercept.
intptr_t sum_two(Numbers foo) {
  return sum_two_impl(foo);
}
