* Build Description

A list of files and a list of unversioned dependencies without specifying where to find them.

Written by a human. Definitely tracked in version control.

#+begin_example
library(foo)
sources(foo.c)
includes(include/)
depends(libfmt)
#+end_example

#+begin_example
program(myprog)
sources(main.c help.c)
includes(include/)
depends(libfmt foo)
#+end_example

#+begin_example
target(mycommand)
runs("echo 'doing things'")
byproducts()
#+end_example

* Build Lockfile

Contains everything the Build Description contains, as well as,
  A) the version of each dependency, and
  B) how to resolve those dependencies.

Generated by the build system, but possibly modified by humans (i.e. to alter requested versions, or prioritize different resolutions). Definitely tracked in version control, for reproducible builds (expected versions).

#+begin_example
versions(libfmt 12.2.0)
resolutions(libfmt https://github.com/fmtlib/fmt)
#+end_example

It is a Lockfile error if a Lockfile does not contain a resolution for a specified dependency. Each dependency *may* contain multiple resolutions, acting as fallbacks.

To upgrade a dependency, you can update the Lockfile, but the build itself doesn't change.
When updating the build process, it will invalidate the Lockfile and generate a new one.

* Build Cache

Contains everything the Lockfile contains, as well as instantiations of recipes .

Generated by the build system. Never even looked at by humans. Definitely *NOT* tracked in version control.

This will cache what compiler, how to pass things to it, what it generates, etc. Like a compile commands json.

* Source Transformer Configurations

Used to configure how to handle sources (extension based) for library and program targets.

#+begin_src cmake
  recipe(
    extensions(g)
    # The library recipe converts $sources into an artifact at $outpath.
    # lcc foo.g bar.g -o libfoo.o
    library("lcc $sources -o $outpath")
    # The program recipe converts $sources into a binary at $outpath.
    # lcc exe.g foo.g bar.g -o exe -b
    program("lcc $sources -o $outpath -b")
  )
  recipe(
    extensions(c)
    # @map(<list>, <variable>, <body>...)
    # for each element bound to <variable>, expand <body> and collect into a
    # list
    # @foreach(<list>, <variable>, <body>...)
    # for each element bound to <variable>, expand <body>
    library(
      set(outs, @map($sources, source, @extension($source, o)))
      @foreach(
        ($sources, $outs),
        (in, out),
        "gcc -c $in -o $out"
      )
      "gcc -c $outs -o $outpath"
    )
    program(
      set(outs, @map($sources, source, @extension($source, o)))
      @foreach(
        ($sources, $outs),
        (in, out),
        "gcc -c $in -o $out"
      )
      "gcc $outs -o $outpath"
    )
  )
#+end_src
