name: CI build and test

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: CMake configure
        run: cmake -G Ninja -B bld
      - name: CMake build
        run: cmake --build bld -j $(nproc)
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v7
      - name: CMake configure
        run: cmake -G Ninja -B bld -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_CXX_SCAN_FOR_MODULES=OFF
      - name: CMake build
        run: cmake --build bld -j $(nproc)
