name: Monthly Distributed Binaries

on:
  schedule:
    - cron: '17 2 1 * *'
  workflow_dispatch:

jobs:
  build-and-package:
    name: CPack ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-26.04, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v7
      - name: CMake Configure
        if: matrix.os != 'windows-latest'
        run: cmake -B bld -DCMAKE_BUILD_TYPE=Release -DNATIVE_OPT=OFF -DPACKAGING=ON
      - name: CMake Configure (Windows)
        if: matrix.os == 'windows-latest'
        run: cmake -B bld -DCMAKE_BUILD_TYPE=Release -DNATIVE_OPT=OFF -DPACKAGING=ON  -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_CXX_SCAN_FOR_MODULES=OFF -DFMT_MODULE=OFF -DUSE_LTO=OFF
      - name: CMake Build
        run: cmake --build bld --config Release
      - name: CPack
        working-directory: bld
        run: cpack -C Release
      - name: Upload Package Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: package-${{ matrix.os }}
          path: |
            bld/*.dmg
            bld/*.exe
            bld/*.msi
            bld/*.pkg
            bld/*.tar.gz
            bld/*.tar.xz
            bld/*.zip
          if-no-files-found: error
  create-release:
    name: Publish Production Release
    needs: build-and-package
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v7
        with:
          path: release-assets
          merge-multiple: true

      - name: Generate Dynamic Version Tag
        id: version
        run: echo "TAG_NAME=v$(date +'0.420.%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.version.outputs.TAG_NAME }}
          name: Monthly Release ${{ steps.version.outputs.TAG_NAME }}
          body: |
            ## Automated Monthly Build
            Distributed binaries packaged via CPack thanks to GitHub Actions Runners.
          draft: false
          prerelease: false
          files: release-assets/*

